name: LightningBan
main: xXSirGamesXx\LightningBan\Main
api: 
- 2.0.0
- 3.0.0
- 3.0.0-ALPHA3
- 3.0.0-ALPHA4
- 3.0.0-ALPHA5
- 3.0.0-ALPHA6
version: 1.1.0
description: "Lightning On Ban"

commands:
  lban:
    description: "Strike Players on ban"
    permission: lbpe.cmd.lban

permissions:
  lbpe.cmd.lban:
    default: op 
    description: "Ban Players with lightning"
