name: LightningBan
main: xXSirGamesXx\LightningBan\Main
api: 
- 2.0.0
- 3.0.0
- 3.0.0-ALPHA3
- 3.0.0-ALPHA4
- 3.0.0-ALPHA5
- 3.0.0-ALPHA6
version: 1.0.1
description: "Lightning On Ban"

commands:
  ban:
    description: "example command description"
    permission: pocketmine.command.ban

permissions:
  pocketmine.command.ban:
    default: true 
    description: "Ban Players with lightning"
