--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/xXSirGamesXx/LightningBan
branches:
- master
projects:
  LightningBan:
    path: ""
    Icon: https://po-cdn-app.azureedge.net/Links/BlobImageProxy/profileoverlayblob?url=%2Fimages%2Fr_s_nES2yk2tEx2wNbN4bA.png
...
